### ISSUE TITLE
follow 주석요청

### ISSUE THREAD

**Issue by kimtaegyu7439** [GC-Project-Space/DB_TEAM-9_twitter#12]
## 설명
> follow / controller, service, repository 주석이 없고 비어있어 어디부터 시작해야 될지 잘 모르겠음..
spring 
## To-do
- [어떤 영상을 참고하면 좋을지 ]
- [주석요청 ]

**Comment by luke0408** [comment]
Users 구현 된거 보면서 작업하면 됩니더
